#ifndef LOX_EITEMTYPES_HPP
#define LOX_EITEMTYPES_HPP

#pragma once

enum EItemTypes
{
    ITEM_TYPE_NONE,
    ITEM_TYPE_MUNDANE,
    ITEM_TYPE_MAGIC,
    ITEM_TYPE_EPIC,
    ITEM_TYPE_ARTIFACT,
    ITEM_TYPE_PSIONIC
};

#endif //LOX_EITEMTYPES_HPP
